# Generated by Django 4.0.1 on 2022-01-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('category', models.CharField(choices=[('act', 'Action'), ('ani', 'Animated'), ('adv', 'Adventurous'), ('bio', 'Biographical'), ('doc', 'Documentary'), ('dra', 'Drama'), ('san', 'Fantasy'), ('hor', 'Horror'), ('his', 'Historically'), ('com', 'Comedies'), ('cri', 'Crime'), ('mys', 'Mysteries'), ('mus', 'Music'), ('fam', 'Family'), ('war', 'War'), ('rom', 'Romantic'), ('sci', 'Sci-Fi'), ('spo', 'Sports'), ('thr', 'Thriller'), ('wes', 'Western')], max_length=3)),
            ],
        ),
    ]
