# Generated by Django 4.0.1 on 2022-01-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_rating_movie_imbd_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='IMBD_rating',
            new_name='IMDb_rating',
        ),
    ]
